- name: variables
  hosts: localhost
  vars:
    course: "Terraform"
    Trainer: "mamatha"
    Duration: "15hrs"
  tasks:

  - name: print information
    ansible.builtin.debug:
      msg: "Hi,we are learning {course} from {{Trainer}}, Duration is {{Duration}}."