- name: variables for prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Enter the Username
    Private: false

  - name: PASSWORD
    prompt: Enter the Password
    Private: true

  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, Username: {{USERNAME}}. Password: {{PASSWORD}}"
