- name: variable from inventory
  hosts: localhost
  tasks:
  - name: print the information
    vars:
      Timings: "08:50AM IST"
    ansible.builtin.debug:
      msg: "hi,learning {{course}} from {{Trainer}}, and the Duration is {{Duration}}. Timings are: {{Timings}}"
