- name: variable preference
  hosts: localhost
  tasks:
  - name: check preference
    ansible.builtin.debug:
      msg: "Hello, Good {{WISHES}}"
    vars:
    WISHES: "Morning from PLAY variable"
 




