- name: var preferences
  hosts: localhost
  tasks:
  vars:
    Name: "Mamatha"
      msg: "Hi,my name is: {{Name}}"

- name: var from args
    msg: "Hi,my name is: {{Name}}"

- name: var from file
  vars_files:
  - 06-vars-file.yaml
      msg: "Hi,my name is: {{Name}}"

  vars_prompt:
  private: false
  ansible.builtin.debug:
    msg: "Hi,my name is: {{Name}}"
 




