- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible') }}"

- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"


- name: lower case
  hosts: localhost
  vars:
    greeting: "HELLO, GOOD MORNING"
  tasks:
  - name: convert into lowercase
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"


- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1, 2, 3, 3, 4, 4, 5]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"


- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [20, 30, 40, 50]
  tasks:
  - name: print min and max
    ansible.builtin.debug:
      msg: " min number: {{ numbers | min }}, max number: {{ numbers | max }}"



- name: converting dictonary into items
  hosts: localhost
  vars:
    my_dict: 
      Course: Devops
      Duration: 120hrs
      Trainer: Mamatha
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "before convert: {{ my_dict }}"
